
function plot_frr_vs_snr_runstar(varargin)
% PLOT_FRR_VS_SNR_RUNSTAR  Reproduce "Plot 1 — FRR vs SNR" using your run_star_tdma pipeline.
%
% This mirrors plot_cdma_frr_compare.m but lets you optionally:
%   - hold a fixed (threshold, accept_ratio) like your original runs, or
%   - calibrate threshold per SNR to hit a target impostor FAR.
%
% Usage (match your old behavior; fixed threshold/accept_ratio):
%   plot_frr_vs_snr_runstar('L',128,'frames',20,'SNRdB_vec',-10:2:12, ...
%                           'threshold',0.8,'accept_ratio',0.8, ...
%                           'use_sic',false,'use_equal_power',true,'rng_seed',1337);
%
% Usage (fixed FAR policy; per-SNR threshold calibration using impostor FAR):
%   plot_frr_vs_snr_runstar('L',128,'frames',20,'SNRdB_vec',-10:2:12, ...
%                           'UseFixedFAR',true,'FARtarget',1e-3, ...
%                           'thr_grid',0.60:0.02:0.98, 'calib_frames',8, ...
%                           'use_sic',false,'use_equal_power',true,'rng_seed',1337);
%
% Name-Value args:
%   'L'               (128)   spreading length
%   'frames'          (20)    Monte Carlo frames per SNR
%   'bits_per_slot'   (128)   payload bits per slot
%   'SNRdB_vec'       (-10:2:12)
%   'use_sic'         (false)
%   'use_equal_power' (true)
%   'rng_seed'        (1337)
%   'threshold'       (0.8)   (used when UseFixedFAR = false)
%   'accept_ratio'    (0.8)   (used when UseFixedFAR = false)
%   'UseFixedFAR'     (false) if true, calibrate tau per SNR to reach FARtarget
%   'FARtarget'       (1e-3)
%   'thr_grid'        (0.60:0.02:0.98) threshold candidates for calibration
%   'calib_frames'    (8)     frames for calibration calls (to keep speed reasonable)
%
% Dependencies: run_star_tdma on MATLAB path.
%
% Output: Figure with FRR vs SNR for K in {1,2,4}, codebooks = {'puf-random','walsh-orth'}

p = inputParser;
addParameter(p,'L',128);
addParameter(p,'frames',20);
addParameter(p,'bits_per_slot',128);
addParameter(p,'SNRdB_vec',-10:2:12);
addParameter(p,'use_sic',false);
addParameter(p,'use_equal_power',true);
addParameter(p,'rng_seed',1337);
addParameter(p,'threshold',0.8);
addParameter(p,'accept_ratio',0.8);
addParameter(p,'UseFixedFAR',false);
addParameter(p,'FARtarget',1e-3);
addParameter(p,'thr_grid',0.60:0.02:0.98);
addParameter(p,'calib_frames',8);
parse(p,varargin{:});
cfg = p.Results;

Ks        = [1 2 4];
codebooks = {'puf-random','walsh-orth'};
numK   = numel(Ks);
numSNR = numel(cfg.SNRdB_vec);
styles = { {'-o','-s','-^'}, {'--o','--s','--^'} };

FRR = nan(numel(codebooks), numK, numSNR);

fprintf('Running run_star_tdma sweeps for FRR vs SNR...\n');
for c = 1:numel(codebooks)
    cb = codebooks{c};
    fprintf('  codebook = %s\n', cb);
    for ik = 1:numK
        K = Ks(ik);
        fprintf('    K = %d ... ', K);

        if ~cfg.UseFixedFAR
            % === Old behavior: fixed (threshold, accept_ratio) across SNR ===
            res = run_star_tdma( ...
                'scheme','CDMA', ...
                'N', max(8, 2*K), ...
                'K_users_per_slot', K, ...
                'cdma_codebook', cb, ...
                'use_slot_dither', true, ...
                'use_equal_power', cfg.use_equal_power, ...
                'use_sic', cfg.use_sic, ...
                'L', cfg.L, ...
                'bits_per_slot', cfg.bits_per_slot, ...
                'frames', cfg.frames, ...
                'SNRdB_vec', cfg.SNRdB_vec, ...
                'threshold', cfg.threshold, ...
                'accept_ratio', cfg.accept_ratio, ...
                'use_nonce', true, ...
                'replay_reuse_prob', 0.0, ...
                'compute_replay_far', false, ...
                'compute_impostor_far', false, ...
                'log_level', 0, ...
                'rng_seed', cfg.rng_seed);
            FRR(c, ik, :) = reshape(res.FRR, 1, 1, []);
        else
            % === Fixed FAR policy: per-SNR calibration of threshold ===
            frr_vec = nan(1, numSNR);
            for is = 1:numSNR
                SNRdB = cfg.SNRdB_vec(is);
                thr_star = calibrate_threshold_fixed_far_runstar( ...
                    'K', K, 'L', cfg.L, 'codebook', cb, 'SNRdB', SNRdB, ...
                    'FARtarget', cfg.FARtarget, 'thr_grid', cfg.thr_grid, ...
                    'frames', cfg.calib_frames, 'bits_per_slot', cfg.bits_per_slot, ...
                    'use_sic', cfg.use_sic, 'use_equal_power', cfg.use_equal_power, ...
                    'rng_seed', cfg.rng_seed);

                res = run_star_tdma( ...
                    'scheme','CDMA', ...
                    'N', max(8, 2*K), ...
                    'K_users_per_slot', K, ...
                    'cdma_codebook', cb, ...
                    'use_slot_dither', true, ...
                    'use_equal_power', cfg.use_equal_power, ...
                    'use_sic', cfg.use_sic, ...
                    'L', cfg.L, ...
                    'bits_per_slot', cfg.bits_per_slot, ...
                    'frames', cfg.frames, ...
                    'SNRdB_vec', SNRdB, ...
                    'threshold', thr_star, ...
                    'accept_ratio', cfg.accept_ratio, ...
                    'use_nonce', true, ...
                    'replay_reuse_prob', 0.0, ...
                    'compute_replay_far', false, ...
                    'compute_impostor_far', false, ...
                    'log_level', 0, ...
                    'rng_seed', cfg.rng_seed);
                frr_vec(is) = res.FRR(1);
            end
            FRR(c, ik, :) = reshape(frr_vec, 1, 1, []);
        end

        fprintf('done.\n');
    end
end

% -------- Plot ----------
figure; hold on; grid on;
% title(sprintf('CDMA FRR vs SNR — PUF-random vs Walsh-orth (L=%d, frames=%d, bits/slot=%d, SIC=%d)', ...
%     cfg.L, cfg.frames, cfg.bits_per_slot, cfg.use_sic));
title(sprintf('CDMA FRR vs SNR — PUF-random vs Walsh-orth (N=%d, bits/slot=%d)', ...
     cfg.L, cfg.bits_per_slot));

xlabel('SNR (dB)'); ylabel('FRR'); ylim([0 1]);
% PUF-random first
c = 1;
for ik = 1:numK
    plot(cfg.SNRdB_vec, squeeze(FRR(c,ik,:))', styles{c}{ik}, 'LineWidth', 1.6, ...
         'DisplayName', sprintf('PUF-rand, K=%d', Ks(ik)));
end
% Walsh-orth overlay
c = 2;
for ik = 1:numK
    plot(cfg.SNRdB_vec, squeeze(FRR(c,ik,:))', styles{c}{ik}, 'LineWidth', 1.6, ...
         'DisplayName', sprintf('Walsh-orth, K=%d', Ks(ik)));
end
legend('Location','northeast'); legend boxoff;
end
