 clear all; clc
%addpath('puf_star_multi');

% CSK with impostor FAR + export
res_csk = run_star_tdma('scheme','CSK', ...
    'N',8, 'M',16, 'L',128, ...
    'SNRdB_vec',-25:5:0, 'frames',100, ...
    'use_node_variation',true,'node_snr_sigma_db',6, ...
    'use_node_similarity',true,'similarity_alpha',0.6, ...
    'use_seed_expansion',true,'threshold',0.8, 'accept_ratio',0.85, ...
    'compute_impostor_far',true, ...
    'compute_impostor_far',true,'compute_replay_far',true, ...
    'replay_reuse_prob',0.6); % ...
    %'export_modeling_csv',false, 'model_csv_path','model_csk.csv');

% CDMA with impostor FAR + export
res_cdma = run_star_tdma('scheme','CDMA', ...
    'N',8, 'L',128, ...
    'SNRdB_vec',-25:5:0, 'frames',100, ...
    'use_node_variation',true,'node_snr_sigma_db',6, ...
    'use_node_similarity',true,'similarity_alpha',0.6, ...
    'use_seed_expansion',true,'threshold',0.8, 'accept_ratio',0.85, ...
    'compute_impostor_far',true, ...
    'compute_impostor_far',true,'compute_replay_far',true, ...
    'replay_reuse_prob',0.6); % ...
    %'export_modeling_csv',false, 'model_csv_path','model_cdma.csv');
